-- MySQL Script generated by MySQL Workbench
-- Wed Jan 24 23:24:21 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema nacnedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nacnedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nacnedb` DEFAULT CHARACTER SET utf8 ;
USE `nacnedb` ;

-- -----------------------------------------------------
-- Table `nacnedb`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nacnedb`.`member` (
  `userid` VARCHAR(16) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `contact` VARCHAR(20) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`userid`),
  UNIQUE INDEX `contact_UNIQUE` (`contact` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nacnedb`.`photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nacnedb`.`photo` (
  `idphoto` INT NOT NULL,
  `uploadDate` TIMESTAMP NULL DEFAULT current_timestamp,
  `userid` VARCHAR(16) NULL,
  `SkinDiseases_disease_id` INT NOT NULL,
  PRIMARY KEY (`idphoto`),
  INDEX `photos_userid_member_idx` (`userid` ASC) VISIBLE,
  CONSTRAINT `photos_userid_member`
    FOREIGN KEY (`userid`)
    REFERENCES `nacnedb`.`member` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nacnedb`.`SkinDiseases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nacnedb`.`SkinDiseases` (
  `disease_id` INT NOT NULL AUTO_INCREMENT,
  `disease_name` VARCHAR(100) NOT NULL,
  `details` TEXT NOT NULL,
  `treatment` TEXT NOT NULL,
  `location` POINT NOT NULL,
  `photo_idphoto` INT NOT NULL,
  PRIMARY KEY (`disease_id`),
  INDEX `fk_SkinDiseases_photo1_idx` (`photo_idphoto` ASC) VISIBLE,
  CONSTRAINT `fk_SkinDiseases_photo1`
    FOREIGN KEY (`photo_idphoto`)
    REFERENCES `nacnedb`.`photo` (`idphoto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nacnedb`.`Progress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nacnedb`.`Progress` (
  `progressid` INT NOT NULL AUTO_INCREMENT,
  `photoid` INT NOT NULL,
  `uploadDate` DATETIME NOT NULL,
  PRIMARY KEY (`progressid`),
  CONSTRAINT `progress_photoid_photo`
    FOREIGN KEY (`progressid`)
    REFERENCES `nacnedb`.`photo` (`idphoto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
